import type { EloMatch } from "../../model/src/index.js";
import type { EloCompatibleMatch } from "./international-elo-adapter.js";

// Curated historical World Cup fixture data (2010, 2014, 2018, 2022) for the live Elo pipeline foundation.
// Matches are pre-sorted chronologically. Each entry includes only the fields required by EloMatch.
// Source: packages/data/fixtures/world-cup — same provenance as the historical validation dataset.
export const LIVE_ELO_FOUNDATION_MATCHES: readonly EloMatch[] = [
  { match_id: "2010-WC-001", match_date: "2010-06-11", home_team: "South Africa", away_team: "Mexico", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-002", match_date: "2010-06-11", home_team: "Uruguay", away_team: "France", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-007", match_date: "2010-06-12", home_team: "South Korea", away_team: "Greece", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-008", match_date: "2010-06-12", home_team: "Argentina", away_team: "Nigeria", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-013", match_date: "2010-06-12", home_team: "England", away_team: "USA", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-014", match_date: "2010-06-13", home_team: "Algeria", away_team: "Slovenia", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-019", match_date: "2010-06-13", home_team: "Serbia", away_team: "Ghana", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-020", match_date: "2010-06-13", home_team: "Germany", away_team: "Australia", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-025", match_date: "2010-06-14", home_team: "Netherlands", away_team: "Denmark", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-026", match_date: "2010-06-14", home_team: "Japan", away_team: "Cameroon", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-031", match_date: "2010-06-14", home_team: "Italy", away_team: "Paraguay", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-032", match_date: "2010-06-15", home_team: "New Zealand", away_team: "Slovakia", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-037", match_date: "2010-06-15", home_team: "Côte d\'Ivoire", away_team: "Portugal", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-038", match_date: "2010-06-15", home_team: "Brazil", away_team: "North Korea", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-003", match_date: "2010-06-16", home_team: "South Africa", away_team: "Uruguay", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-043", match_date: "2010-06-16", home_team: "Honduras", away_team: "Chile", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-044", match_date: "2010-06-16", home_team: "Spain", away_team: "Switzerland", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-004", match_date: "2010-06-17", home_team: "France", away_team: "Mexico", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-009", match_date: "2010-06-17", home_team: "Argentina", away_team: "South Korea", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-010", match_date: "2010-06-17", home_team: "Greece", away_team: "Nigeria", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-015", match_date: "2010-06-18", home_team: "Slovenia", away_team: "USA", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-016", match_date: "2010-06-18", home_team: "England", away_team: "Algeria", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-021", match_date: "2010-06-18", home_team: "Germany", away_team: "Serbia", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-022", match_date: "2010-06-19", home_team: "Ghana", away_team: "Australia", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-027", match_date: "2010-06-19", home_team: "Netherlands", away_team: "Japan", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-028", match_date: "2010-06-19", home_team: "Cameroon", away_team: "Denmark", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-033", match_date: "2010-06-20", home_team: "Slovakia", away_team: "Paraguay", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-034", match_date: "2010-06-20", home_team: "Italy", away_team: "New Zealand", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-039", match_date: "2010-06-20", home_team: "Brazil", away_team: "Côte d\'Ivoire", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-040", match_date: "2010-06-21", home_team: "Portugal", away_team: "North Korea", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-045", match_date: "2010-06-21", home_team: "Chile", away_team: "Switzerland", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-046", match_date: "2010-06-21", home_team: "Spain", away_team: "Honduras", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-005", match_date: "2010-06-22", home_team: "Mexico", away_team: "Uruguay", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-006", match_date: "2010-06-22", home_team: "France", away_team: "South Africa", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-011", match_date: "2010-06-22", home_team: "Nigeria", away_team: "South Korea", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-012", match_date: "2010-06-22", home_team: "Greece", away_team: "Argentina", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-017", match_date: "2010-06-23", home_team: "USA", away_team: "Algeria", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-018", match_date: "2010-06-23", home_team: "Slovenia", away_team: "England", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-023", match_date: "2010-06-23", home_team: "Australia", away_team: "Serbia", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-024", match_date: "2010-06-23", home_team: "Ghana", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-029", match_date: "2010-06-24", home_team: "Denmark", away_team: "Japan", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-030", match_date: "2010-06-24", home_team: "Cameroon", away_team: "Netherlands", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-035", match_date: "2010-06-24", home_team: "Slovakia", away_team: "Italy", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-036", match_date: "2010-06-24", home_team: "Paraguay", away_team: "New Zealand", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-041", match_date: "2010-06-25", home_team: "Portugal", away_team: "Brazil", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-042", match_date: "2010-06-25", home_team: "North Korea", away_team: "Côte d\'Ivoire", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-047", match_date: "2010-06-25", home_team: "Chile", away_team: "Spain", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-048", match_date: "2010-06-25", home_team: "Switzerland", away_team: "Honduras", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-049", match_date: "2010-06-26", home_team: "Uruguay", away_team: "South Korea", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-050", match_date: "2010-06-26", home_team: "USA", away_team: "Ghana", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-051", match_date: "2010-06-27", home_team: "Germany", away_team: "England", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-052", match_date: "2010-06-27", home_team: "Argentina", away_team: "Mexico", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-053", match_date: "2010-06-28", home_team: "Netherlands", away_team: "Slovakia", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-054", match_date: "2010-06-28", home_team: "Brazil", away_team: "Chile", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-055", match_date: "2010-06-29", home_team: "Paraguay", away_team: "Japan", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-056", match_date: "2010-06-29", home_team: "Spain", away_team: "Portugal", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-057", match_date: "2010-07-02", home_team: "Netherlands", away_team: "Brazil", neutral_site: true, result: "home_win" },
  { match_id: "2010-WC-058", match_date: "2010-07-02", home_team: "Uruguay", away_team: "Ghana", neutral_site: true, result: "draw" },
  { match_id: "2010-WC-059", match_date: "2010-07-03", home_team: "Argentina", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-060", match_date: "2010-07-03", home_team: "Paraguay", away_team: "Spain", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-061", match_date: "2010-07-06", home_team: "Uruguay", away_team: "Netherlands", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-062", match_date: "2010-07-07", home_team: "Germany", away_team: "Spain", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-063", match_date: "2010-07-10", home_team: "Uruguay", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2010-WC-064", match_date: "2010-07-11", home_team: "Netherlands", away_team: "Spain", neutral_site: true, result: "away_win" },
  // 2014 World Cup
  { match_id: "2014-WC-001", match_date: "2014-06-12", home_team: "Brazil", away_team: "Croatia", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-002", match_date: "2014-06-13", home_team: "Mexico", away_team: "Cameroon", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-007", match_date: "2014-06-13", home_team: "Spain", away_team: "Netherlands", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-008", match_date: "2014-06-13", home_team: "Chile", away_team: "Australia", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-013", match_date: "2014-06-14", home_team: "Colombia", away_team: "Greece", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-014", match_date: "2014-06-14", home_team: "Côte d\'Ivoire", away_team: "Japan", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-019", match_date: "2014-06-14", home_team: "Uruguay", away_team: "Costa Rica", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-020", match_date: "2014-06-14", home_team: "England", away_team: "Italy", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-025", match_date: "2014-06-15", home_team: "Switzerland", away_team: "Ecuador", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-026", match_date: "2014-06-15", home_team: "France", away_team: "Honduras", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-031", match_date: "2014-06-15", home_team: "Argentina", away_team: "Bosnia-Herzegovina", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-032", match_date: "2014-06-16", home_team: "Iran", away_team: "Nigeria", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-037", match_date: "2014-06-16", home_team: "Germany", away_team: "Portugal", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-038", match_date: "2014-06-16", home_team: "Ghana", away_team: "USA", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-003", match_date: "2014-06-17", home_team: "Brazil", away_team: "Mexico", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-043", match_date: "2014-06-17", home_team: "Belgium", away_team: "Algeria", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-044", match_date: "2014-06-17", home_team: "Russia", away_team: "South Korea", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-004", match_date: "2014-06-18", home_team: "Cameroon", away_team: "Croatia", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-009", match_date: "2014-06-18", home_team: "Australia", away_team: "Netherlands", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-010", match_date: "2014-06-18", home_team: "Spain", away_team: "Chile", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-015", match_date: "2014-06-19", home_team: "Colombia", away_team: "Côte d\'Ivoire", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-016", match_date: "2014-06-19", home_team: "Japan", away_team: "Greece", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-021", match_date: "2014-06-19", home_team: "Uruguay", away_team: "England", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-022", match_date: "2014-06-20", home_team: "Italy", away_team: "Costa Rica", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-027", match_date: "2014-06-20", home_team: "Switzerland", away_team: "France", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-028", match_date: "2014-06-20", home_team: "Honduras", away_team: "Ecuador", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-033", match_date: "2014-06-21", home_team: "Argentina", away_team: "Iran", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-034", match_date: "2014-06-21", home_team: "Nigeria", away_team: "Bosnia-Herzegovina", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-039", match_date: "2014-06-21", home_team: "Germany", away_team: "Ghana", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-040", match_date: "2014-06-22", home_team: "USA", away_team: "Portugal", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-045", match_date: "2014-06-22", home_team: "Belgium", away_team: "Russia", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-046", match_date: "2014-06-22", home_team: "South Korea", away_team: "Algeria", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-005", match_date: "2014-06-23", home_team: "Cameroon", away_team: "Brazil", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-006", match_date: "2014-06-23", home_team: "Croatia", away_team: "Mexico", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-011", match_date: "2014-06-23", home_team: "Australia", away_team: "Spain", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-012", match_date: "2014-06-23", home_team: "Netherlands", away_team: "Chile", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-017", match_date: "2014-06-24", home_team: "Japan", away_team: "Colombia", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-018", match_date: "2014-06-24", home_team: "Greece", away_team: "Côte d\'Ivoire", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-023", match_date: "2014-06-24", home_team: "Italy", away_team: "Uruguay", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-024", match_date: "2014-06-24", home_team: "Costa Rica", away_team: "England", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-029", match_date: "2014-06-25", home_team: "Honduras", away_team: "Switzerland", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-030", match_date: "2014-06-25", home_team: "Ecuador", away_team: "France", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-035", match_date: "2014-06-25", home_team: "Nigeria", away_team: "Argentina", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-036", match_date: "2014-06-25", home_team: "Bosnia-Herzegovina", away_team: "Iran", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-041", match_date: "2014-06-26", home_team: "USA", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-042", match_date: "2014-06-26", home_team: "Portugal", away_team: "Ghana", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-047", match_date: "2014-06-26", home_team: "South Korea", away_team: "Belgium", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-048", match_date: "2014-06-26", home_team: "Algeria", away_team: "Russia", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-049", match_date: "2014-06-28", home_team: "Brazil", away_team: "Chile", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-050", match_date: "2014-06-28", home_team: "Colombia", away_team: "Uruguay", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-051", match_date: "2014-06-29", home_team: "Netherlands", away_team: "Mexico", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-052", match_date: "2014-06-29", home_team: "Costa Rica", away_team: "Greece", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-053", match_date: "2014-06-30", home_team: "France", away_team: "Nigeria", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-054", match_date: "2014-06-30", home_team: "Germany", away_team: "Algeria", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-055", match_date: "2014-07-01", home_team: "Argentina", away_team: "Switzerland", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-056", match_date: "2014-07-01", home_team: "Belgium", away_team: "USA", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-057", match_date: "2014-07-04", home_team: "France", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-058", match_date: "2014-07-04", home_team: "Brazil", away_team: "Colombia", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-059", match_date: "2014-07-05", home_team: "Argentina", away_team: "Belgium", neutral_site: true, result: "home_win" },
  { match_id: "2014-WC-060", match_date: "2014-07-05", home_team: "Netherlands", away_team: "Costa Rica", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-061", match_date: "2014-07-08", home_team: "Brazil", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-062", match_date: "2014-07-09", home_team: "Netherlands", away_team: "Argentina", neutral_site: true, result: "draw" },
  { match_id: "2014-WC-063", match_date: "2014-07-12", home_team: "Brazil", away_team: "Netherlands", neutral_site: true, result: "away_win" },
  { match_id: "2014-WC-064", match_date: "2014-07-13", home_team: "Germany", away_team: "Argentina", neutral_site: true, result: "home_win" },
  // 2018 World Cup
  { match_id: "2018-WC-001", match_date: "2018-06-14", home_team: "Russia", away_team: "Saudi Arabia", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-002", match_date: "2018-06-15", home_team: "Egypt", away_team: "Uruguay", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-007", match_date: "2018-06-15", home_team: "Morocco", away_team: "Iran", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-008", match_date: "2018-06-15", home_team: "Portugal", away_team: "Spain", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-013", match_date: "2018-06-16", home_team: "France", away_team: "Australia", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-014", match_date: "2018-06-16", home_team: "Peru", away_team: "Denmark", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-019", match_date: "2018-06-16", home_team: "Argentina", away_team: "Iceland", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-020", match_date: "2018-06-16", home_team: "Croatia", away_team: "Nigeria", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-025", match_date: "2018-06-17", home_team: "Costa Rica", away_team: "Serbia", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-026", match_date: "2018-06-17", home_team: "Brazil", away_team: "Switzerland", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-031", match_date: "2018-06-17", home_team: "Germany", away_team: "Mexico", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-032", match_date: "2018-06-18", home_team: "Sweden", away_team: "South Korea", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-037", match_date: "2018-06-18", home_team: "Belgium", away_team: "Panama", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-038", match_date: "2018-06-18", home_team: "Tunisia", away_team: "England", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-003", match_date: "2018-06-19", home_team: "Russia", away_team: "Egypt", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-043", match_date: "2018-06-19", home_team: "Colombia", away_team: "Japan", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-044", match_date: "2018-06-19", home_team: "Poland", away_team: "Senegal", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-004", match_date: "2018-06-20", home_team: "Uruguay", away_team: "Saudi Arabia", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-009", match_date: "2018-06-20", home_team: "Portugal", away_team: "Morocco", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-010", match_date: "2018-06-20", home_team: "Iran", away_team: "Spain", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-015", match_date: "2018-06-21", home_team: "Denmark", away_team: "Australia", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-016", match_date: "2018-06-21", home_team: "France", away_team: "Peru", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-021", match_date: "2018-06-21", home_team: "Argentina", away_team: "Croatia", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-022", match_date: "2018-06-22", home_team: "Nigeria", away_team: "Iceland", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-027", match_date: "2018-06-22", home_team: "Brazil", away_team: "Costa Rica", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-028", match_date: "2018-06-22", home_team: "Serbia", away_team: "Switzerland", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-033", match_date: "2018-06-23", home_team: "South Korea", away_team: "Mexico", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-034", match_date: "2018-06-23", home_team: "Germany", away_team: "Sweden", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-039", match_date: "2018-06-23", home_team: "Belgium", away_team: "Tunisia", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-040", match_date: "2018-06-24", home_team: "England", away_team: "Panama", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-045", match_date: "2018-06-24", home_team: "Japan", away_team: "Senegal", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-046", match_date: "2018-06-24", home_team: "Poland", away_team: "Colombia", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-005", match_date: "2018-06-25", home_team: "Uruguay", away_team: "Russia", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-006", match_date: "2018-06-25", home_team: "Saudi Arabia", away_team: "Egypt", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-011", match_date: "2018-06-25", home_team: "Iran", away_team: "Portugal", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-012", match_date: "2018-06-25", home_team: "Spain", away_team: "Morocco", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-017", match_date: "2018-06-26", home_team: "Denmark", away_team: "France", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-018", match_date: "2018-06-26", home_team: "Australia", away_team: "Peru", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-023", match_date: "2018-06-26", home_team: "Nigeria", away_team: "Argentina", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-024", match_date: "2018-06-26", home_team: "Iceland", away_team: "Croatia", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-029", match_date: "2018-06-27", home_team: "Serbia", away_team: "Brazil", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-030", match_date: "2018-06-27", home_team: "Switzerland", away_team: "Costa Rica", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-035", match_date: "2018-06-27", home_team: "South Korea", away_team: "Germany", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-036", match_date: "2018-06-27", home_team: "Mexico", away_team: "Sweden", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-041", match_date: "2018-06-28", home_team: "England", away_team: "Belgium", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-042", match_date: "2018-06-28", home_team: "Panama", away_team: "Tunisia", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-047", match_date: "2018-06-28", home_team: "Japan", away_team: "Poland", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-048", match_date: "2018-06-28", home_team: "Senegal", away_team: "Colombia", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-049", match_date: "2018-06-30", home_team: "France", away_team: "Argentina", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-050", match_date: "2018-06-30", home_team: "Uruguay", away_team: "Portugal", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-051", match_date: "2018-07-01", home_team: "Spain", away_team: "Russia", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-052", match_date: "2018-07-01", home_team: "Croatia", away_team: "Denmark", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-053", match_date: "2018-07-02", home_team: "Brazil", away_team: "Mexico", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-054", match_date: "2018-07-02", home_team: "Belgium", away_team: "Japan", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-055", match_date: "2018-07-03", home_team: "Sweden", away_team: "Switzerland", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-056", match_date: "2018-07-03", home_team: "Colombia", away_team: "England", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-057", match_date: "2018-07-06", home_team: "Uruguay", away_team: "France", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-058", match_date: "2018-07-06", home_team: "Brazil", away_team: "Belgium", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-059", match_date: "2018-07-07", home_team: "Sweden", away_team: "England", neutral_site: true, result: "away_win" },
  { match_id: "2018-WC-060", match_date: "2018-07-07", home_team: "Russia", away_team: "Croatia", neutral_site: true, result: "draw" },
  { match_id: "2018-WC-061", match_date: "2018-07-10", home_team: "France", away_team: "Belgium", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-062", match_date: "2018-07-11", home_team: "Croatia", away_team: "England", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-063", match_date: "2018-07-14", home_team: "Belgium", away_team: "England", neutral_site: true, result: "home_win" },
  { match_id: "2018-WC-064", match_date: "2018-07-15", home_team: "France", away_team: "Croatia", neutral_site: true, result: "home_win" },
  // 2022 World Cup
  { match_id: "2022-WC-001", match_date: "2022-11-20", home_team: "Qatar", away_team: "Ecuador", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-002", match_date: "2022-11-21", home_team: "Senegal", away_team: "Netherlands", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-007", match_date: "2022-11-21", home_team: "England", away_team: "Iran", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-008", match_date: "2022-11-21", home_team: "USA", away_team: "Wales", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-013", match_date: "2022-11-22", home_team: "Argentina", away_team: "Saudi Arabia", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-014", match_date: "2022-11-22", home_team: "Mexico", away_team: "Poland", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-019", match_date: "2022-11-22", home_team: "Denmark", away_team: "Tunisia", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-020", match_date: "2022-11-22", home_team: "France", away_team: "Australia", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-025", match_date: "2022-11-23", home_team: "Germany", away_team: "Japan", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-026", match_date: "2022-11-23", home_team: "Spain", away_team: "Costa Rica", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-031", match_date: "2022-11-23", home_team: "Morocco", away_team: "Croatia", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-032", match_date: "2022-11-23", home_team: "Belgium", away_team: "Canada", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-037", match_date: "2022-11-24", home_team: "Switzerland", away_team: "Cameroon", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-038", match_date: "2022-11-24", home_team: "Brazil", away_team: "Serbia", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-043", match_date: "2022-11-24", home_team: "Uruguay", away_team: "South Korea", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-044", match_date: "2022-11-24", home_team: "Portugal", away_team: "Ghana", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-003", match_date: "2022-11-25", home_team: "Qatar", away_team: "Senegal", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-004", match_date: "2022-11-25", home_team: "Netherlands", away_team: "Ecuador", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-009", match_date: "2022-11-25", home_team: "Wales", away_team: "Iran", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-010", match_date: "2022-11-25", home_team: "England", away_team: "USA", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-015", match_date: "2022-11-26", home_team: "Poland", away_team: "Saudi Arabia", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-016", match_date: "2022-11-26", home_team: "Argentina", away_team: "Mexico", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-021", match_date: "2022-11-26", home_team: "Tunisia", away_team: "Australia", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-022", match_date: "2022-11-26", home_team: "France", away_team: "Denmark", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-027", match_date: "2022-11-27", home_team: "Japan", away_team: "Costa Rica", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-028", match_date: "2022-11-27", home_team: "Spain", away_team: "Germany", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-033", match_date: "2022-11-27", home_team: "Belgium", away_team: "Morocco", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-034", match_date: "2022-11-27", home_team: "Croatia", away_team: "Canada", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-039", match_date: "2022-11-28", home_team: "Cameroon", away_team: "Serbia", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-040", match_date: "2022-11-28", home_team: "Brazil", away_team: "Switzerland", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-045", match_date: "2022-11-28", home_team: "South Korea", away_team: "Ghana", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-046", match_date: "2022-11-28", home_team: "Portugal", away_team: "Uruguay", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-005", match_date: "2022-11-29", home_team: "Ecuador", away_team: "Senegal", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-006", match_date: "2022-11-29", home_team: "Netherlands", away_team: "Qatar", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-011", match_date: "2022-11-29", home_team: "Wales", away_team: "England", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-012", match_date: "2022-11-29", home_team: "Iran", away_team: "USA", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-017", match_date: "2022-11-30", home_team: "Poland", away_team: "Argentina", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-018", match_date: "2022-11-30", home_team: "Saudi Arabia", away_team: "Mexico", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-023", match_date: "2022-11-30", home_team: "Australia", away_team: "Denmark", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-024", match_date: "2022-11-30", home_team: "Tunisia", away_team: "France", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-029", match_date: "2022-12-01", home_team: "Japan", away_team: "Spain", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-030", match_date: "2022-12-01", home_team: "Costa Rica", away_team: "Germany", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-035", match_date: "2022-12-01", home_team: "Croatia", away_team: "Belgium", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-036", match_date: "2022-12-01", home_team: "Canada", away_team: "Morocco", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-041", match_date: "2022-12-02", home_team: "Serbia", away_team: "Switzerland", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-042", match_date: "2022-12-02", home_team: "Cameroon", away_team: "Brazil", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-047", match_date: "2022-12-02", home_team: "Ghana", away_team: "Uruguay", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-048", match_date: "2022-12-02", home_team: "South Korea", away_team: "Portugal", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-049", match_date: "2022-12-03", home_team: "Netherlands", away_team: "USA", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-050", match_date: "2022-12-03", home_team: "Argentina", away_team: "Australia", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-051", match_date: "2022-12-04", home_team: "France", away_team: "Poland", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-052", match_date: "2022-12-04", home_team: "England", away_team: "Senegal", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-053", match_date: "2022-12-05", home_team: "Japan", away_team: "Croatia", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-054", match_date: "2022-12-05", home_team: "Brazil", away_team: "South Korea", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-055", match_date: "2022-12-06", home_team: "Morocco", away_team: "Spain", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-056", match_date: "2022-12-06", home_team: "Portugal", away_team: "Switzerland", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-057", match_date: "2022-12-09", home_team: "Croatia", away_team: "Brazil", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-058", match_date: "2022-12-09", home_team: "Netherlands", away_team: "Argentina", neutral_site: true, result: "draw" },
  { match_id: "2022-WC-059", match_date: "2022-12-10", home_team: "Morocco", away_team: "Portugal", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-060", match_date: "2022-12-10", home_team: "England", away_team: "France", neutral_site: true, result: "away_win" },
  { match_id: "2022-WC-061", match_date: "2022-12-13", home_team: "Argentina", away_team: "Croatia", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-062", match_date: "2022-12-14", home_team: "France", away_team: "Morocco", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-063", match_date: "2022-12-17", home_team: "Croatia", away_team: "Morocco", neutral_site: true, result: "home_win" },
  { match_id: "2022-WC-064", match_date: "2022-12-18", home_team: "Argentina", away_team: "France", neutral_site: true, result: "draw" },
];

export const LIVE_ELO_FOUNDATION_DATA_SCOPE = "world_cup_2010_2014_2018_2022" as const;
export const LIVE_ELO_FOUNDATION_LATEST_MATCH_DATE = "2022-12-18" as const;
export const LIVE_ELO_FOUNDATION_TOURNAMENT_COUNT = 4 as const;
export const LIVE_ELO_FOUNDATION_MATCH_COUNT = 256 as const;

export const LIVE_ELO_INTERNATIONAL_SUPPLEMENT_MATCH_COUNT = 12 as const;
export const LIVE_ELO_INTERNATIONAL_SUPPLEMENT_LATEST_MATCH_DATE = "2024-09-07" as const;
export const LIVE_ELO_INTERNATIONAL_SUPPLEMENT_DATA_SCOPE =
  "world_cup_2022_copa_america_2024_euro_2024_wcq_2026_international_friendly" as const;

export const LIVE_ELO_INTERNATIONAL_SUPPLEMENT: readonly EloCompatibleMatch[] = [
  { match_id: "INT-COPA24-001", match_date: "2024-07-14", home_team: "Argentina", away_team: "Colombia", neutral_site: true, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "INT-COPA24-002", match_date: "2024-07-09", home_team: "Argentina", away_team: "Canada", neutral_site: true, home_score: 2, away_score: 0, result: "home_win" },
  { match_id: "INT-COPA24-003", match_date: "2024-07-10", home_team: "Colombia", away_team: "Uruguay", neutral_site: true, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "INT-EURO24-001", match_date: "2024-07-14", home_team: "Spain", away_team: "England", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "INT-EURO24-002", match_date: "2024-07-09", home_team: "Spain", away_team: "France", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "INT-EURO24-003", match_date: "2024-07-10", home_team: "England", away_team: "Netherlands", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "INT-WCQ26-001", match_date: "2023-10-12", home_team: "Argentina", away_team: "Paraguay", neutral_site: false, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "INT-WCQ26-002", match_date: "2023-10-12", home_team: "Brazil", away_team: "Venezuela", neutral_site: false, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "INT-WCQ26-003", match_date: "2024-09-07", home_team: "Germany", away_team: "Hungary", neutral_site: false, home_score: 5, away_score: 0, result: "home_win" },
  { match_id: "INT-FRI-001", match_date: "2023-09-12", home_team: "Germany", away_team: "France", neutral_site: false, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "INT-FRI-002", match_date: "2024-03-26", home_team: "Spain", away_team: "Brazil", neutral_site: false, home_score: 3, away_score: 3, result: "draw" },
  { match_id: "INT-FRI-003", match_date: "2024-06-06", home_team: "Morocco", away_team: "USA", neutral_site: false, home_score: 3, away_score: 0, result: "home_win" },
];

export const LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT_DATASET_ID = "international-matches-expanded-v1" as const;
export const LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT_MATCH_COUNT = 56 as const;
export const LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT_LATEST_MATCH_DATE = "2024-07-14" as const;

export const LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT: readonly EloCompatibleMatch[] = [
  { match_id: "EXP-WC22-001", match_date: "2022-11-20", home_team: "Qatar", away_team: "Ecuador", neutral_site: true, home_score: 0, away_score: 2, result: "away_win" },
  { match_id: "EXP-WC22-002", match_date: "2022-11-21", home_team: "England", away_team: "Iran", neutral_site: true, home_score: 6, away_score: 2, result: "home_win" },
  { match_id: "EXP-WC22-003", match_date: "2022-11-22", home_team: "Argentina", away_team: "Saudi Arabia", neutral_site: true, home_score: 1, away_score: 2, result: "away_win" },
  { match_id: "EXP-WC22-004", match_date: "2022-11-22", home_team: "France", away_team: "Australia", neutral_site: true, home_score: 4, away_score: 1, result: "home_win" },
  { match_id: "EXP-WC22-005", match_date: "2022-11-23", home_team: "Germany", away_team: "Japan", neutral_site: true, home_score: 1, away_score: 2, result: "away_win" },
  { match_id: "EXP-WC22-006", match_date: "2022-11-23", home_team: "Spain", away_team: "Costa Rica", neutral_site: true, home_score: 7, away_score: 0, result: "home_win" },
  { match_id: "EXP-WC22-007", match_date: "2022-12-03", home_team: "Netherlands", away_team: "USA", neutral_site: true, home_score: 3, away_score: 1, result: "home_win" },
  { match_id: "EXP-WC22-008", match_date: "2022-12-03", home_team: "Argentina", away_team: "Australia", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-WC22-009", match_date: "2022-12-09", home_team: "Netherlands", away_team: "Argentina", neutral_site: true, home_score: 2, away_score: 2, result: "draw" },
  { match_id: "EXP-WC22-010", match_date: "2022-12-13", home_team: "Argentina", away_team: "Croatia", neutral_site: true, home_score: 3, away_score: 0, result: "home_win" },
  { match_id: "EXP-WC22-011", match_date: "2022-12-14", home_team: "France", away_team: "Morocco", neutral_site: true, home_score: 2, away_score: 0, result: "home_win" },
  { match_id: "EXP-WC22-012", match_date: "2022-12-18", home_team: "Argentina", away_team: "France", neutral_site: true, home_score: 3, away_score: 3, result: "draw" },
  { match_id: "EXP-COPA24-001", match_date: "2024-06-20", home_team: "Argentina", away_team: "Canada", neutral_site: true, home_score: 2, away_score: 0, result: "home_win" },
  { match_id: "EXP-COPA24-002", match_date: "2024-06-21", home_team: "Peru", away_team: "Chile", neutral_site: true, home_score: 0, away_score: 0, result: "draw" },
  { match_id: "EXP-COPA24-003", match_date: "2024-06-22", home_team: "Ecuador", away_team: "Venezuela", neutral_site: true, home_score: 1, away_score: 2, result: "away_win" },
  { match_id: "EXP-COPA24-004", match_date: "2024-06-23", home_team: "USA", away_team: "Bolivia", neutral_site: false, home_score: 2, away_score: 0, result: "home_win" },
  { match_id: "EXP-COPA24-005", match_date: "2024-06-23", home_team: "Uruguay", away_team: "Panama", neutral_site: true, home_score: 3, away_score: 1, result: "home_win" },
  { match_id: "EXP-COPA24-006", match_date: "2024-06-24", home_team: "Colombia", away_team: "Paraguay", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-COPA24-007", match_date: "2024-06-24", home_team: "Brazil", away_team: "Costa Rica", neutral_site: true, home_score: 0, away_score: 0, result: "draw" },
  { match_id: "EXP-COPA24-008", match_date: "2024-06-27", home_team: "Panama", away_team: "USA", neutral_site: false, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-COPA24-009", match_date: "2024-06-28", home_team: "Colombia", away_team: "Costa Rica", neutral_site: true, home_score: 3, away_score: 0, result: "home_win" },
  { match_id: "EXP-COPA24-010", match_date: "2024-07-04", home_team: "Argentina", away_team: "Ecuador", neutral_site: true, home_score: 1, away_score: 1, result: "draw" },
  { match_id: "EXP-COPA24-011", match_date: "2024-07-09", home_team: "Argentina", away_team: "Canada", neutral_site: true, home_score: 2, away_score: 0, result: "home_win" },
  { match_id: "EXP-COPA24-012", match_date: "2024-07-10", home_team: "Colombia", away_team: "Uruguay", neutral_site: true, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "EXP-COPA24-013", match_date: "2024-07-14", home_team: "Argentina", away_team: "Colombia", neutral_site: true, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "EXP-EURO24-001", match_date: "2024-06-14", home_team: "Germany", away_team: "Scotland", neutral_site: false, home_score: 5, away_score: 1, result: "home_win" },
  { match_id: "EXP-EURO24-002", match_date: "2024-06-15", home_team: "Hungary", away_team: "Switzerland", neutral_site: true, home_score: 1, away_score: 3, result: "away_win" },
  { match_id: "EXP-EURO24-003", match_date: "2024-06-15", home_team: "Spain", away_team: "Croatia", neutral_site: true, home_score: 3, away_score: 0, result: "home_win" },
  { match_id: "EXP-EURO24-004", match_date: "2024-06-15", home_team: "Italy", away_team: "Albania", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-EURO24-005", match_date: "2024-06-16", home_team: "Poland", away_team: "Netherlands", neutral_site: true, home_score: 1, away_score: 2, result: "away_win" },
  { match_id: "EXP-EURO24-006", match_date: "2024-06-16", home_team: "Serbia", away_team: "England", neutral_site: true, home_score: 0, away_score: 1, result: "away_win" },
  { match_id: "EXP-EURO24-007", match_date: "2024-06-17", home_team: "Austria", away_team: "France", neutral_site: true, home_score: 0, away_score: 1, result: "away_win" },
  { match_id: "EXP-EURO24-008", match_date: "2024-06-18", home_team: "Portugal", away_team: "Czech Republic", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-EURO24-009", match_date: "2024-07-05", home_team: "Spain", away_team: "Germany", neutral_site: false, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-EURO24-010", match_date: "2024-07-09", home_team: "Spain", away_team: "France", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-EURO24-011", match_date: "2024-07-10", home_team: "Netherlands", away_team: "England", neutral_site: true, home_score: 1, away_score: 2, result: "away_win" },
  { match_id: "EXP-EURO24-012", match_date: "2024-07-14", home_team: "Spain", away_team: "England", neutral_site: true, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-WCQ26-001", match_date: "2023-09-07", home_team: "Paraguay", away_team: "Peru", neutral_site: false, home_score: 0, away_score: 0, result: "draw" },
  { match_id: "EXP-WCQ26-002", match_date: "2023-09-07", home_team: "Colombia", away_team: "Venezuela", neutral_site: false, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "EXP-WCQ26-003", match_date: "2023-09-07", home_team: "Argentina", away_team: "Ecuador", neutral_site: false, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "EXP-WCQ26-004", match_date: "2023-09-08", home_team: "Uruguay", away_team: "Chile", neutral_site: false, home_score: 3, away_score: 1, result: "home_win" },
  { match_id: "EXP-WCQ26-005", match_date: "2023-09-08", home_team: "Brazil", away_team: "Bolivia", neutral_site: false, home_score: 5, away_score: 1, result: "home_win" },
  { match_id: "EXP-WCQ26-006", match_date: "2023-09-12", home_team: "Bolivia", away_team: "Argentina", neutral_site: false, home_score: 0, away_score: 3, result: "away_win" },
  { match_id: "EXP-WCQ26-007", match_date: "2023-09-12", home_team: "Ecuador", away_team: "Uruguay", neutral_site: false, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-WCQ26-008", match_date: "2023-09-12", home_team: "Venezuela", away_team: "Paraguay", neutral_site: false, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "EXP-WCQ26-009", match_date: "2023-09-12", home_team: "Peru", away_team: "Brazil", neutral_site: false, home_score: 0, away_score: 1, result: "away_win" },
  { match_id: "EXP-WCQ26-010", match_date: "2023-10-12", home_team: "Argentina", away_team: "Paraguay", neutral_site: false, home_score: 1, away_score: 0, result: "home_win" },
  { match_id: "EXP-WCQ26-011", match_date: "2023-10-12", home_team: "Colombia", away_team: "Uruguay", neutral_site: false, home_score: 2, away_score: 2, result: "draw" },
  { match_id: "EXP-WCQ26-012", match_date: "2023-10-12", home_team: "Brazil", away_team: "Venezuela", neutral_site: false, home_score: 1, away_score: 1, result: "draw" },
  { match_id: "EXP-FRI-001", match_date: "2023-09-12", home_team: "Germany", away_team: "France", neutral_site: false, home_score: 2, away_score: 1, result: "home_win" },
  { match_id: "EXP-FRI-002", match_date: "2024-03-23", home_team: "France", away_team: "Germany", neutral_site: false, home_score: 0, away_score: 2, result: "away_win" },
  { match_id: "EXP-FRI-003", match_date: "2024-03-26", home_team: "England", away_team: "Belgium", neutral_site: false, home_score: 2, away_score: 2, result: "draw" },
  { match_id: "EXP-FRI-004", match_date: "2024-03-26", home_team: "Spain", away_team: "Brazil", neutral_site: false, home_score: 3, away_score: 3, result: "draw" },
  { match_id: "EXP-FRI-005", match_date: "2024-03-22", home_team: "Spain", away_team: "Colombia", neutral_site: true, home_score: 0, away_score: 1, result: "away_win" },
  { match_id: "EXP-FRI-006", match_date: "2024-06-08", home_team: "Mexico", away_team: "Brazil", neutral_site: true, home_score: 2, away_score: 3, result: "away_win" },
  { match_id: "EXP-FRI-007", match_date: "2024-06-08", home_team: "USA", away_team: "Colombia", neutral_site: false, home_score: 1, away_score: 5, result: "away_win" },
];

export interface LiveEloInternationalSupplementLoadResult {
  matches: readonly EloCompatibleMatch[];
  metadata: {
    datasetId: string;
    matchCount: number;
    competitions: readonly string[];
    latestMatchDate: string | undefined;
    warningCodes: readonly string[];
    foundationWarnings: readonly string[];
  };
  fallbackUsed: boolean;
  loadWarnings: readonly string[];
}

function fallbackSupplementLoadResult(reason: string): LiveEloInternationalSupplementLoadResult {
  return {
    matches: LIVE_ELO_INTERNATIONAL_SUPPLEMENT,
    metadata: {
      datasetId: "international-matches-inline-fallback-v1",
      matchCount: LIVE_ELO_INTERNATIONAL_SUPPLEMENT_MATCH_COUNT,
      competitions: ["Copa America 2024", "FIFA World Cup 2026 Qualifier", "International Friendly", "UEFA Euro 2024"],
      latestMatchDate: LIVE_ELO_INTERNATIONAL_SUPPLEMENT_LATEST_MATCH_DATE,
      warningCodes: ["partial_international_history", "curated_sample_only", "not_complete_global_match_history"],
      foundationWarnings: [
        "partial_international_history: inline fallback supplement covers selected competitions and dates only.",
        "curated_sample_only: inline fallback supplement is manually selected for lightweight validation coverage.",
        "not_complete_global_match_history: inline fallback supplement is not a complete global senior international match database."
      ]
    },
    fallbackUsed: true,
    loadWarnings: [`Expanded international supplement unavailable; using inline supplement fallback. ${reason}`]
  };
}

export function loadLiveEloInternationalSupplement(): LiveEloInternationalSupplementLoadResult {
  if (LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT.length === 0) {
    return fallbackSupplementLoadResult("expanded supplement has no matches.");
  }

  return {
    matches: LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT,
    metadata: {
      datasetId: LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT_DATASET_ID,
      matchCount: LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT_MATCH_COUNT,
      competitions: [
        "Copa America 2024",
        "FIFA World Cup 2022",
        "FIFA World Cup 2026 Qualifier",
        "International Friendly",
        "UEFA Euro 2024"
      ],
      latestMatchDate: LIVE_ELO_EXPANDED_INTERNATIONAL_SUPPLEMENT_LATEST_MATCH_DATE,
      warningCodes: ["partial_international_history", "curated_sample_only", "not_complete_global_match_history"],
      foundationWarnings: [
        "partial_international_history: expanded supplement covers selected competitions and dates only.",
        "curated_sample_only: expanded supplement is manually selected for lightweight validation coverage.",
        "not_complete_global_match_history: expanded supplement is not a complete global senior international match database."
      ]
    },
    fallbackUsed: false,
    loadWarnings: []
  };
}
